CREATE TABLE [dbo].[Table]
(
	[ID_MEMBRE] INT NOT NULL PRIMARY KEY, 
    [NOM_MEMRE] NCHAR(100) NULL, 
    [MOT_DE_PASSE] NCHAR(100) NULL, 
    [STATUT] NCHAR(30) NULL, 
    [CONTACT] NCHAR(250) NULL
)
