//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_03_VRAI
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBRES
    {
        public MEMBRES()
        {
            this.OFFRE = new HashSet<OFFRE>();
        }
    
        public int ID_MEMBRE { get; set; }
        public string NOM_MEMBRE { get; set; }
        public string MOT_DE_PASSE { get; set; }
        public string STATUT { get; set; }
        public string CONTACT { get; set; }
    
        public virtual ICollection<OFFRE> OFFRE { get; set; }
    }
}
