//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_03_VRAI
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFFRE
    {
        public int ID_OFFRE { get; set; }
        public int ID_MEMBRE { get; set; }
        public int ID_ITEM { get; set; }
        public double PRIX_OFFRE { get; set; }
        public Nullable<System.DateTime> DATE_OFFRE { get; set; }
    
        public virtual ITEM ITEM { get; set; }
        public virtual MEMBRES MEMBRES { get; set; }
    }
}
